// Shared domain model. Mirrors the single-table DynamoDB layout described in infra/README.md.

export type Role = "owner" | "admin" | "viewer";
export type PlanId = "free" | "growth" | "enterprise";
export type Framework = "gdpr" | "ccpa" | "dpdpa" | "generic";
export type CategoryId = "essential" | "functional" | "analytics" | "marketing";
export type Layout = "bar" | "modal" | "toast";
export type Position = "bottom" | "top" | "bottom-left" | "bottom-right" | "center";

export interface User {
  id: string;
  email: string;
  name: string;
  /** scrypt hash, local auth driver only. Cognito users have no password stored here. */
  passwordHash?: string;
  createdAt: string;
}

export interface Organization {
  id: string;
  name: string;
  plan: PlanId;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  /** AWS region consent receipts are pinned to (data residency). */
  dataRegion: "ap-south-1" | "ap-south-2" | "eu-central-1" | "us-east-1";
  dpo?: { name: string; email: string; address?: string };
  createdAt: string;
}

export interface Membership {
  orgId: string;
  userId: string;
  role: Role;
  createdAt: string;
}

export interface Invite {
  id: string;
  orgId: string;
  email: string;
  role: Role;
  createdAt: string;
}

export interface CategoryCopy {
  id: CategoryId;
  label: string;
  description: string;
  /** essential categories are always on and cannot be declined */
  required: boolean;
}

export interface BannerCopy {
  title: string;
  body: string;
  acceptAll: string;
  rejectAll: string;
  customize: string;
  save: string;
  /** link shown at the end of the body */
  policyLabel: string;
}

export interface BannerTheme {
  layout: Layout;
  position: Position;
  background: string;
  text: string;
  accent: string;
  accentText: string;
  radius: number;
  font: "system" | "inherit" | "serif" | "mono";
  /** equal-weight buttons: reject is as prominent as accept (required for GDPR/DPDPA, no dark patterns) */
  equalButtons: boolean;
}

export interface RegionRule {
  framework: Framework;
  /** ISO-3166 alpha-2 country codes, or "EU" / "IN" / "US-CA" groups resolved in geo.ts */
  enabled: boolean;
  /** opt-in requires explicit consent; opt-out pre-enables non-essential categories with a "Do not sell" link */
  model: "opt-in" | "opt-out";
  copy: BannerCopy;
  language: string;
}

export interface BannerConfig {
  version: number;
  theme: BannerTheme;
  categories: CategoryCopy[];
  regions: Record<Framework, RegionRule>;
  policyUrl: string;
  /** headless: SDK loads rules + blocking but renders no UI; site supplies its own via window.PlainConsent */
  headless: boolean;
  /** Google Consent Mode v2 signals */
  googleConsentMode: boolean;
  /** days before re-asking */
  expiryDays: number;
}

export interface Tracker {
  id: string;
  name: string;
  category: CategoryId;
  /** substring or hostname matched against script src */
  pattern: string;
}

export interface Property {
  id: string;
  orgId: string;
  name: string;
  domain: string;
  /** public site key embedded in the snippet */
  siteKey: string;
  config: BannerConfig;
  trackers: Tracker[];
  publishedVersion: number;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export type ConsentAction = "accept_all" | "reject_all" | "custom" | "revoke" | "dismiss";

export interface ConsentReceipt {
  id: string;
  propertyId: string;
  /** anonymous visitor id generated by the SDK (random, not derived from PII) */
  visitorId: string;
  action: ConsentAction;
  framework: Framework;
  categories: Record<CategoryId, boolean>;
  country: string;
  device: "desktop" | "mobile" | "tablet";
  browser: string;
  /** truncated then salted-hashed IP; the raw IP is never stored */
  ipHash: string;
  configVersion: number;
  timestamp: string;
  /** sha256(prevHash + canonical(receipt)) — forms a tamper-evident chain per property */
  prevHash: string;
  hash: string;
  seq: number;
}

export interface PageviewCounter {
  propertyId: string;
  /** YYYY-MM-DD */
  day: string;
  views: number;
  /** banner shown, no interaction before leaving */
  bounces: number;
}
