/** Consent categories. `essential` is always allowed and never blocked. */
export type Category = "essential" | "functional" | "analytics" | "marketing";

/** The notice shown to a visitor, chosen from their location. */
export type Framework = "gdpr" | "ccpa" | "dpdpa" | "generic";

export type Categories = Record<Category, boolean>;

export interface ConsentState {
  framework: Framework;
  categories: Categories;
  /** true once the visitor has made a choice for the current config version */
  decided: boolean;
  /** random id generated by the script, never derived from personal data */
  visitorId: string;
}

export type ConsentEvent = "change" | "ready";

/** The `window.PlainConsent` API exposed by plain-consent.js. */
export interface PlainConsentApi {
  version: string;
  get(): ConsentState;
  acceptAll(): void;
  rejectAll(): void;
  set(partial: Partial<Categories>): void;
  open(): void;
  revoke(): void;
  on(event: ConsentEvent, fn: (state: ConsentState) => void): () => void;
  push(fn: (api: PlainConsentApi) => void): void;
  /** Dashboard preview helper. Not needed in applications. */
  preview(config: unknown, framework?: Framework, view?: "banner" | "prefs"): void;
}

export interface LoadOptions {
  /** Your public site key from the dashboard's Install page. */
  siteKey: string;
  /** Script URL. Defaults to the Plain Theory CDN, or `{origin of apiUrl}/sdk/plain-consent.js` when `apiUrl` is set. */
  src?: string;
  /** API base for receipts and events (`data-api`). Defaults to the script's origin + /api/v1. */
  apiUrl?: string;
  /** Published config URL (`data-config-url`). Defaults to `{apiUrl}/config/{siteKey}`. */
  configUrl?: string;
  /** Allow `?plain_country=` location overrides outside localhost (`data-debug`). */
  debug?: boolean;
  /** Resolve the load promise after this many ms even if the config hasn't arrived. Default 8000. */
  readyTimeoutMs?: number;
  /** Optional CSP nonce for the injected script tag. */
  nonce?: string;
}
